

services:
  tabled_app:
    image: xiaoyao9184/tabled:0.1.4
    container_name: tabled_pdf_app
    environment:
      - TORCH_DEVICE=cpu
      - HF_HUB_OFFLINE=true
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_det3/snapshots/467ee9ec33e6e6c5f73e57dbc1415b14032f5b95
      - LAYOUT_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_layout3/snapshots/6f4c319b213ddbe736c9fe6de87ad7dc3bbb0a1e
      - ORDER_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_order/snapshots/7b727d0a2c942cdc8596d186115f65c12c812bd8
      - RECOGNITION_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_rec2/snapshots/6611509b2c3a32c141703ce19adc899d9d0abf41
      - TABLE_REC_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_tablerec/snapshots/8bca165f81e9cee5fb382413eb23175079917d14
    ports:
      - "8501:8501"
    volumes:
      - ./../../cache:/root/.cache
