ARG TABLED_VERSION=0.1.6
ARG STREAMLIT_VERSION=1.40.2

FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime

ARG TABLED_VERSION
ARG STREAMLIT_VERSION

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir tabled-pdf==${TABLED_VERSION} streamlit==${STREAMLIT_VERSION}

EXPOSE 8501

VOLUME /root/.cache

CMD ["tabled_gui"]
