

services:
  tabled_app:
    image: xiaoyao9184/tabled:master
    container_name: tabled_pdf_app
    environment:
      - TORCH_DEVICE=cpu
    ports:
      - "8501:8501"
    volumes:
      - ./../../cache:/root/.cache
